### PR TITLE
Refuse to arm unless throttle stick is down and switches are at the correct positions

### LINKED ISSUE #110: Refuse to fly unless the switches are at the correct positions
Additional safety measure: The quadcopter should refuse to fly when the script starts unless the switches are at the correct positions (A: up, B: up, C: first position, D: down) **and** the throttle stick is fully down. In fact the buzzer should make a sound. Since we can control the buzzer only from the ESP, it should be good to implement this on the ESP.

### LINKED ISSUE #165: Kill motors when receiver gets disconnected
### Describe the bug

We need to make sure that the motors are killed in case the receiver seems to be disconnected for more than a few milliseconds. We had tested it a few weeks ago, and the motors kept spinning after unplugging the receiver. 

### Affected File

_No response_

### Affected Line

_No response_

### To Reproduce

Remove the receiver wires

### Minimum reproducible example

Guys, we should simplify bug reporting! 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jamie-54**
## Main Changes

The quadcopter will not arm unless all switches are up except the arm switch (switch B) and the throttle is less than 5%

## Associated Issues

Closes #110 

## Tests

Test that quadcopter will not arm

### CODE REVIEW

File: src/raspberryEsp32Interface.cpp [hunk 1]
```diff
@@ -155,7 +155,7 @@ namespace bzzz
 
     bool RaspberryEsp32Interface::armed()
     {
-        return m_encodedSwitchesData & RADIO_SWITCH_B_BIT;
+        return m_encodedSwitchesData == RADIO_SWITCH_B_BIT && throttleReferencePercentage() < 0.05 ;
```
Comment (alphaville) [inline src/raspberryEsp32Interface.cpp:158]: `RADIO_SWITCH_B_BIT` is the *position* of the bits. I think this should be something like

```c++
bool isArmSwitchOn = m_encodedSwitchesData & RADIO_SWITCH_B_BIT;
bool isThrottleDown = throttleReferencePercentage() < 0.05;
return isArmSwitchOn && isThrottleDown;
```

Comment (alphaville) [inline src/raspberryEsp32Interface.cpp:158]: Is 5% low enough? Should we make it 0 instead?

Comment (jamie-54) [reply src/raspberryEsp32Interface.cpp:158]: Yea 5% seems to be low enough (the motors don't spin), 

I didn't want to set it to zero encase the actual value sent from receiver isn't exactly 0% e.g. expects value 300 receives 301. anyway we should make this a variable as well in the config file

**Review by alphaville — APPROVED** [review]
Looks good - let's merge this. Next, we should deal with #165 and #175.

**Comment by jamie-54** [comment]
I'm just after testing this on the quadcopter and it seems to be working.

It also starts to address #175 
When the quadcopter is killed all the switches need to be correct and the throttle down to un-kill it. think we just need to add a Timmer in to solve #175 properly

**Comment by alphaville** [comment]
@jamie-54 Brilliant! If it works, let's merge this one.

**Comment by alphaville** [comment]
@jamie-54 regarding #175, I guess you'll do this in Python. You want to count about 3s and the accuracy isn't too important. You just need to store in memory a timestamp of the last time the kill switch was flipped and use something like

```py
import time
time_since_killed = time_killed - time.time()
if time_since_killed >= 3:
   # cannot unkill directly...
```

File: include/config.hpp [hunk 2]
```diff
@@ -48,6 +48,12 @@
  */
 #define BUZZER_PIN 27
 
+/**
+ * Maximum throttle percentage for arming the motors
+ * The throttle stick must be less than this percentage to arm the motors
+ */
+#define MAX_ARMING_THROTTLE_PERCENTAGE 0.05
```
Comment (alphaville) [inline include/config.hpp:55]: Should this be `MIN_ARMING_THROTTLE_PERCENTAGE`? (min instead of max)

File: src/main.cpp [hunk 3]
```diff
@@ -20,6 +20,11 @@ float yawReferenceRad = 0.0;
 float initialAngularVelocity[3];
 float IMUData[6];
 int motorFL, motorFR, motorBL, motorBR;
+bool wasKill=0;
+bool isKill=0;
+unsigned long timestampLastKill = 0;
+bool isThrottleStickDown = 0;
+bool allowUnkill=1;
```
Comment (alphaville) [inline src/main.cpp:27]: We're not using `allowUnkill`

File: src/main.cpp [hunk 4]
```diff
@@ -87,15 +93,50 @@ void loop()
...
+            isKill, wasKill, timestampLastKill);
   }
+
+  
+  // If you're attempting to resurrect it...
+  // K --> U
+  if (!isKill && wasKill){
+    // If you're too late, you need to pull the stick down
+    unsigned long timeElapsedSinceKill = millis() - timestampLastKill;
+    if (timeElapsedSinceKill >= 3000) {
```
Comment (alphaville) [inline src/main.cpp:110]: Make 3000 into a global constant variable

File: src/main.cpp [hunk 5]
```diff
@@ -87,15 +93,50 @@ void loop()
...
+        logSerial(LogVerbosityLevel::Debug, "ET: %lu, isThrottleStickDown: %d\n", timeElapsedSinceKill, isThrottleStickDown);
+        if (isThrottleStickDown){
```
Comment (alphaville) [inline src/main.cpp:112]: We can simplify this as follows:

```py
if (!isThrottleStickDown){
    motorDriver.disarm();
    isKill = 1;
    return;
  }
```

File: src/main.cpp [hunk 6]
```diff
@@ -87,15 +93,50 @@ void loop()
...
+          // proceed - unkill
+        } else { 
+          motorDriver.disarm();
+          isKill = 1;
+          return;
+        }
+    } else {
```
Comment (alphaville) [inline src/main.cpp:119]: We can drop this `else` too

File: src/main.cpp [hunk 7]
```diff
@@ -87,15 +93,50 @@ void loop()
...
   }
+
+  
+  // If you're attempting to resurrect it...
+  // K --> U
+  if (!isKill && wasKill){
+    // If you're too late, you need to pull the stick down
+    unsigned long timeElapsedSinceKill = millis() - timestampLastKill;
+    if (timeElapsedSinceKill >= 3000) {
+        logSerial(LogVerbosityLevel::Debug, "ET: %lu, isThrottleStickDown: %d\n", timeElapsedSinceKill, isThrottleStickDown);
```
Comment (alphaville) [inline src/main.cpp:111]: Before we merge this, let us remove these `logSerial` statements

File: include/config.hpp (hunk 2 above)
Comment (jamie-54) [reply include/config.hpp:55]: Think max is right because it will still arm if percentage throttle is less than 5%

File: src/raspberryEsp32Interface.cpp [hunk 8]
```diff
@@ -148,14 +148,22 @@ namespace bzzz
...
         //=> percentage = Reference_PWM/1000 - 1
         return m_refData[RADIO_CHANNEL_THROTTLE] / 1000 - 1;
     }
 
+    bool RaspberryEsp32Interface::switchA()
+    {
+        return m_encodedSwitchesData & RADIO_SWITCH_A_BIT;
+    }
+    
     bool RaspberryEsp32Interface::armed()
```
[the remark this answers is not in the document]
Comment (jamie-54) [reply src/raspberryEsp32Interface.cpp:161]: Think we should keep it `==` that means all the switches have to be in the correct place to arm

[the remark this answers is not in the document]
Comment (alphaville) [reply src/raspberryEsp32Interface.cpp:161]: Ah, yes! Maybe, let's put a comment there.

**Comment by jamie-54** [comment]
I've tested and the current version works on the quadcopter

File: src/raspberryEsp32Interface.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (jamie-54) [reply src/raspberryEsp32Interface.cpp:161]: I think the way it is now is the way it needs to be I've added comments

[the remark this answers is not in the document]
Comment (alphaville) [reply src/raspberryEsp32Interface.cpp]: @jamie-54, I renamed this to `canArm`, because it doesn't return whether the motors *are* armed, but whether they can be armed. The only place where we use this function is in the function `waitForArmCommand`:

```c++
void RaspberryEsp32Interface::waitForArmCommand()
{
    float temp[6];
    readPiData();
    sendFlightDataToPi(-1, -1, -1, -1, -1, -1, -1, -1, -1, -1);
    delay(20);
    while (!canArm())
    {
        readPiData();
        sendFlightDataToPi(-1, -1, -1, -1, -1, -1, -1, -1, -1, -1);
    }
}
```

If you're happy with this change we can merge this.

[the remark this answers is not in the document]
Comment (jamie-54) [reply src/raspberryEsp32Interface.cpp]: Yea that makes sense thanks, I'm happy to merge
